"""empty message

Revision ID: 226ff6cc3b6a
Revises: d19b8fa6c999
Create Date: 2018-03-06 20:55:23.199583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226ff6cc3b6a'
down_revision = 'd19b8fa6c999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
