"""blog content markdown

Revision ID: cecbd70bcb8d
Revises: 85ea0927e2be
Create Date: 2018-03-07 22:10:24.991082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cecbd70bcb8d'
down_revision = '85ea0927e2be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'content_html')
    # ### end Alembic commands ###
